---
version: '3'

services:
  annovar:
    container_name: annovar
    build:
      context: build
      args:
        http_proxy: ${http_proxy}
    image: dceoy/annovar:latest
    user: ${UID}:${GID}
    userns_mode: host
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
    volumes:
      - .:/wd
      - ./bin:/opt/bin
    working_dir: /wd
    entrypoint:
      - /opt/bin/annovar_cli.sh
    command:
      - --db-dir=./humandb
      - --out-dir=./output
      - --downdb
      - /usr/local/src/annovar/example/ex2.vcf
